name: Release build
on: [workflow_dispatch]

jobs:
  build:
    name: Release build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install third party libraries
        shell: pwsh
        run: ./InstallThirdPartyLibraries.ps1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build solution
        shell: pwsh
        run: msbuild /m CppCoverage.sln /p:Configuration=Release /p:Platform=x64

      - name: Build MSI
        shell: pwsh
        run: msbuild OpenCppCoverage.wixproj /p:Configuration=Release

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MSI
          path: bin/Release/OpenCppCoverage.msi
          if-no-files-found: error
          compression-level: 6
          retention-days: 14
